# --- !Ups

CREATE TABLE "LOGIN" ("USERNAME" VARCHAR NOT NULL PRIMARY KEY, "PASSWORD" VARCHAR NOT NULL);
CREATE TABLE "TASKLIST" ("ID" SERIAL PRIMARY KEY, "TITLE" VARCHAR NOT NULL, "BODY" VARCHAR NOT NULL, "USERNAME" VARCHAR NOT NULL, FOREIGN KEY ("USERNAME") REFERENCES "LOGIN"("USERNAME"));


# --- !Downs

DROP TABLE "LOGIN" CASCADE;
DROP TABLE "TASKLIST";



