# --- !Ups

CREATE TABLE "TASKLIST" ("TITLE" VARCHAR NOT NULL PRIMARY KEY, "BODY" VARCHAR NOT NULL);
CREATE TABLE "LOGIN" ("USERNAME" VARCHAR NOT NULL PRIMARY KEY, "PASSWORD" VARCHAR NOT NULL);

# --- !Downs

DROP TABLE "TASKLIST";
DROP TABLE "LOGIN";
